# Generated by Django 6.0.2 on 2026-05-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
