# Generated by Django 6.0.2 on 2026-06-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rank_note_alter_rank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wing',
            field=models.CharField(blank=True, choices=[('army', 'Army'), ('navy', 'Navy'), ('air_force', 'Air Force'), ('civil', 'Civil'), ('school', 'School')], max_length=20, null=True),
        ),
    ]
