# Authentication
POST http://localhost:8020/api/v1/accounts/login/
POST http://localhost:8020/api/v1/accounts/refresh/
POST http://localhost:8020/api/v1/accounts/verify-otp/
POST http://localhost:8020/api/v1/accounts/resend-otp/
POST http://localhost:8020/api/v1/accounts/forgot-password/
POST http://localhost:8020/api/v1/accounts/verify-reset-otp/
POST http://localhost:8020/api/v1/accounts/reset-password/
PUT http://localhost:8020/api/v1/accounts/password/change/

# Permissions
ALL_METHOD http://localhost:8020/api/v1/rbac/roles/ 
GET http://localhost:8020/api/v1/rbac/permissions/


# Roles
ALL_METHOD http://localhost:8020/api/v1/accounts/ranks/
ALL_METHOD http://localhost:8020/api/v1/accounts/users/


@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4NTIwODcyLCJpYXQiOjE3NzU5Mjg4NzIsImp0aSI6IjJmNmQ5Yzg1NTYxMzQ3MmE4OGM1Y2ZkZTFjOGRkMjExIiwiaWQiOiJiNGNmNGVjNy02YWM5LTRkM2ItYmNhNS0xZDc1NGFlMmE1ODcifQ.Nmg00o7gxSdyJTlYqZr9nlMBNkrCozkVZs6BB-s39dc


### Registration
POST http://localhost:8020/api/v1/accounts/register/  
Content-Type: application/json

{
    "first_name": "AN",
    "last_name": "Mamun",
    "email": "anmamuncoder@gmail.com",
    "password": "securepassword123"
}

### Login
POST http://localhost:8020/api/v1/accounts/login/
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123"
}

### Token Refresh
POST http://localhost:8020/api/v1/accounts/refresh/
Content-Type: application/json

{
     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3ODUxOTQxMSwiaWF0IjoxNzc1OTI3NDExLCJqdGkiOiJkMGFhMDJjYTE1ZGI0OTMzOGIzNjY5NjQxNDAzYjQ5OSIsImlkIjoiYjRjZjRlYzctNmFjOS00ZDNiLWJjYTUtMWQ3NTRhZTJhNTg3In0.Fq88aHyPUZPAlhCPgs44L6wOsje-0towNjhDpUOsfRQ"
}

### OTP Verification
POST http://localhost:8020/api/v1/accounts/verify-otp/
Content-Type: application/json

{
    "email": "anmamuncoder@gmail.com",
    "otp": "590240"
}

### Resend OTP
POST http://localhost:8020/api/v1/accounts/resend-otp/
Content-Type: application/json

{
    "email": "anmamuncoder@gmail.com"
}


# -------------

###  
POST http://localhost:8020/api/v1/accounts/forgot-password/
Content-Type: application/json

{
    "email": "anmamuncoder@gmail.com"
}

###  
POST http://localhost:8020/api/v1/accounts/verify-reset-otp/
Content-Type: application/json

{
    "email": "anmamuncoder@gmail.com",
    "otp": "433191"
}

###  
POST http://localhost:8020/api/v1/accounts/reset-password/
Content-Type: application/json

{
    "reset_token": "StrpPRUp3XAGUTCZdzsMNX6vTPa0ht3nk6Myj0xe7Pg",
    "new_password": "123456789"
}


# -------------
# Authentication:

###
PUT http://localhost:8020/api/v1/accounts/password/change/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3ODg5OTY2LCJpYXQiOjE3NzUyOTc5NjYsImp0aSI6IjVmNGI5Mjc3Nzk5YzQxY2JhYjI2ZGNmYTA1MDIwNmFlIiwiaWQiOiI0M2M4NGYyMC1mNDU5LTRmN2QtOTJhMy03ZDViNzc2NTNjMDAifQ.vVN79GblndwBXvbhiplmZ7lh2QBU6CcJM51mBV5AUE4
Content-Type: application/json

{
    "current_password":"1234567890",
    "new_password":"123456789012",
    "confirm_password":"123456789012"
}

#success message:
# {
#   "success": true,
#   "message": "Password updated successfully.",
#   "data": null
# }

# current password is wrong if;
# {
#   "status": false,
#   "errors": {
#     "current_password": [
#       "Current password is incorrect."
#     ]
#   }
# }

###
POST http://localhost:8020/api/v1/accounts/email/change/
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
    "new_email":"fokhrul.dev@gmail.com",
    "password":"123456789"
}

# success message
# {
#   "success": true,
#   "message": "OTP sent to anmamuncoder@gmail.com.",
#   "data": null
# }

# error if same email:
# {
#   "status": false,
#   "errors": {
#     "new_email": [
#       "New email must be different from current email."
#     ]
#   }
# }
# if wrong password:

# {
#   "status": false,
#   "errors": {
#     "password": [
#       "Incorrect password."
#     ]
#   }
# }
# if use this email ayone 

# {
#   "status": false,
#   "errors": {
#     "new_email": [
#       "This email is already in use."
#     ]
#   }
# }


###
POST http://localhost:8020/api/v1/accounts/email/change/verify/
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
    "otp":"373579"
}

# {
#   "success": true,
#   "message": "Email updated successfully.",
#   "data": null
# }

# {
#   "status": false,
#   "errors": {
#     "otp": [
#       "Invalid OTP."
#     ]
#   }
# }

@superuser_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4NTIxMDM3LCJpYXQiOjE3NzU5MjkwMzcsImp0aSI6ImRmYWZmNmRlMzE5ZjRmOGNiNmMzNTA3NDIwZWFjNWE1IiwiaWQiOiI4NGI3MWNmZC1iMDMwLTQ2ZDAtYjEyYy01OTY1YTE0YTAzZTQifQ.1bSSC23Gbl3OJ6A5R3EEJmjuALeKK7dBEHs1XwNrz0k

# --------------------------------------
# Permissions  - Only Admin
# --------------------------------------
### admin
GET http://localhost:8020/api/v1/rbac/permissions/self/
Authorization:  Bearer {{access_token}}

### admin
GET http://localhost:8020/api/v1/rbac/permissions/accounts_ranks:create/
Authorization:  Bearer {{superuser_token}}
# {
#   "id": "3096301b-5f43-42aa-9ea0-89966c239f1d",
#   "slug": "order:delete",
#   "name": "Delete order test",
#   "resource": "order",
#   "action": "delete",
#   "description": "",
#   "created_at": "2026-03-23T00:12:47.258577+06:00",
#   "updated_at": "2026-03-24T15:25:03.821205+06:00"
# }

### admin
PATCH  http://localhost:8020/api/v1/rbac/permissions/order:delete/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw
Content-Type: application/json

{
    "name":"Delete order test" 
  
}

### admin
PATCH  http://localhost:8020/api/v1/rbac/permissions/order:delete/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw
Content-Type: application/json

{
    "name":"Delete order test" 
}


# ---------------------------------
# Roles - only for Admin
# ---------------------------------


### 
GET http://localhost:8020/api/v1/rbac/roles/
Authorization:  Bearer {{access_token}}


#   {
#     "id": "71b00eaa-526f-48bc-be0e-795fe2194930",
#     "name": "Editor",
#     "slug": "editor",
#     "permissions": [
#       "order:create",
#       "product:create",
#       "product:update",
#       "product:view"
#     ],
#     "description": "",
#     "created_at": "2026-03-23T00:12:47.290573+06:00",
#     "updated_at": "2026-03-24T01:33:34.241815+06:00"
#   },

###
POST http://localhost:8020/api/v1/rbac/roles/ 
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw
Content-Type: application/json

###
GET http://localhost:8020/api/v1/rbac/roles/teacher/
Authorization:  Bearer {{superuser_token}}

###
GET  http://localhost:8020/api/v1/rbac/roles/editor/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw

###
DELETE  http://localhost:8020/api/v1/rbac/roles/slug/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw

# ---------------------------------
# UserRole - only for Admin
# ---------------------------------
GET http://localhost:8020/api/v1/rbac/user-roles/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ1NDgwLCJpYXQiOjE3NzQzNDQ1ODAsImp0aSI6IjQ0YjIyY2NlY2E0MzRmYjZhOGZlNTU3MjU1ZmZmODU3IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.kDW2V0l3-p-olOBSNB8o4Q91WZLFJ9bnwG38jIegIqQ

### admin
GET http://localhost:8020/api/v1/rbac/user-roles/ae6ecf0d-3a7d-4b56-bcfc-0beff9255ac6/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ1NDgwLCJpYXQiOjE3NzQzNDQ1ODAsImp0aSI6IjQ0YjIyY2NlY2E0MzRmYjZhOGZlNTU3MjU1ZmZmODU3IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.kDW2V0l3-p-olOBSNB8o4Q91WZLFJ9bnwG38jIegIqQ

# {
#   "id": "ae6ecf0d-3a7d-4b56-bcfc-0beff9255ac6",
#   "user": "anmamuncoder@gmail.com",
#   "role": "manager"
# }

### admin
PATCH http://localhost:8020/api/v1/rbac/user-roles/ae6ecf0d-3a7d-4b56-bcfc-0beff9255ac6/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ1NDgwLCJpYXQiOjE3NzQzNDQ1ODAsImp0aSI6IjQ0YjIyY2NlY2E0MzRmYjZhOGZlNTU3MjU1ZmZmODU3IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.kDW2V0l3-p-olOBSNB8o4Q91WZLFJ9bnwG38jIegIqQ
Content-Type: application/json

{  
    "role": "editor"
}

### admin
POST http://localhost:8020/api/v1/rbac/user-roles/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ1NDgwLCJpYXQiOjE3NzQzNDQ1ODAsImp0aSI6IjQ0YjIyY2NlY2E0MzRmYjZhOGZlNTU3MjU1ZmZmODU3IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.kDW2V0l3-p-olOBSNB8o4Q91WZLFJ9bnwG38jIegIqQ
Content-Type: application/json

{  
  "user": "anmamuncoder@gmail.com",
  "role": "editor"
}

### admin
GET http://localhost:8020/api/v1/rbac/user-roles-assign/
Authorization:  Bearer {{superuser_token}}
 

### admin
POST  http://localhost:8020/api/v1/rbac/user-roles-assign/
Authorization:  Bearer {{superuser_token}}
Content-Type: application/json

{
    "user": "anmamuncoder@gmail.com",
    "role": "teacher"
}

### admin
PATCH   http://localhost:8020/api/v1/rbac/user-roles-assign/a56a30a6-f86a-4ea4-b891-6e1d5d50ad06/
Authorization:  Bearer {{superuser_token}}
Content-Type: application/json

{ 
    "role": "librarian"
}


# ---------------------------------
# User Ranks
# ---------------------------------
###
GET http://localhost:8020/api/v1/students/students/
Authorization:  Bearer {{superuser_token}}

### BASE URL
@studentUrl = http://127.0.0.1:8000/api/v1/students

@admin-token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4MTgyNTQ0LCJpYXQiOjE3NzU1OTA1NDQsImp0aSI6ImQ2NTk0YzVkNTgyZTQwMWE4YmFjYTM1OWY2MjhhZGQ4IiwiaWQiOiI0ZWViMzc1YS1kNzBjLTQ2ODMtODk5YS1kZWFlYzFmZmM0YjEifQ.PVwkA6Y0Wd8gQN1Dwc10AgZ5itmGchfunTABUkUnXwI

 
 
# Permissions
ALL_METHOD http://localhost:8020/api/v1/rbac/roles/ 
GET http://localhost:8020/api/v1/rbac/permissions/


# Roles
ALL_METHOD http://localhost:8020/api/v1/accounts/ranks/
ALL_METHOD http://localhost:8020/api/v1/accounts/users/

# Student Related
ALL http://localhost:8020/api/v1/students/students/
ALL http://localhost:8020/api/v1/students/student-types/
ALL http://localhost:8020/api/v1/students/student-groups/
ALL http://localhost:8020/api/v1/students/activities/
ALL http://localhost:8020/api/v1/students/spouses/
ALL http://localhost:8020/api/v1/students/qualifications/
ALL http://localhost:8020/api/v1/students/bank-accounts/
ALL http://localhost:8020/api/v1/students/military-qualifications/
ALL http://localhost:8020/api/v1/students/service-records/
ALL http://localhost:8020/api/v1/students/awards/
ALL http://localhost:8020/api/v1/students/un-missions/
ALL http://localhost:8020/api/v1/students/countries-visited/


# Courses 
 
ALL http://localhost:8020/api/v1/courses/courses/
ALL http://localhost:8020/api/v1/courses/subjects/
ALL http://localhost:8020/api/v1/courses/modules/
ALL http://localhost:8020/api/v1/courses/syllabus/
ALL http://localhost:8020/api/v1/courses/detail-syllabus/
ALL http://localhost:8020/api/v1/courses/batches/

