# Authentication
POST http://localhost:8020/api/v1/accounts/login/
POST http://localhost:8020/api/v1/accounts/refresh/
POST http://localhost:8020/api/v1/accounts/verify-otp/
POST http://localhost:8020/api/v1/accounts/resend-otp/
POST http://localhost:8020/api/v1/accounts/forgot-password/
POST http://localhost:8020/api/v1/accounts/verify-reset-otp/
POST http://localhost:8020/api/v1/accounts/reset-password/
PUT http://localhost:8020/api/v1/accounts/password/change/

# Permissions
ALL_METHOD http://localhost:8020/api/v1/rbac/roles/ 
GET http://localhost:8020/api/v1/rbac/permissions/


# Roles
ALL_METHOD http://localhost:8020/api/v1/accounts/ranks/
ALL_METHOD http://localhost:8020/api/v1/accounts/users/


@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4OTU4NzIzLCJpYXQiOjE3NzYzNjY3MjMsImp0aSI6ImE1YjIxZWMzYTI5YTQ3YjZhN2RmYWU4ODIwYzEzMjY3IiwiaWQiOiI4NGI3MWNmZC1iMDMwLTQ2ZDAtYjEyYy01OTY1YTE0YTAzZTQifQ.b7ISD8b3NRqPKsughR1a6t-pt1bJZXS1X1yHgfQ60Ck

### Registration
POST http://localhost:8020/api/v1/accounts/register/  
Content-Type: application/json

{
    "first_name": "AN",
    "last_name": "Mamun",
    "email": "anmamuncoder@gmail.com",
    "password": "securepassword123"
}
###
GET https://backend.dipstick.xyz/api/v1/students/student-types/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5MDkyOTcxLCJpYXQiOjE3NzY1MDA5NzIsImp0aSI6ImI2MjljM2Y5ZTMwYjRiNDZhMmM2NDY2ZWI0MGQ4NGZiIiwiaWQiOiI4NGI3MWNmZC1iMDMwLTQ2ZDAtYjEyYy01OTY1YTE0YTAzZTQifQ.CkUCY5Xf5NAblk7YkcGfqRRWzX4tTl2FCL_ShPxQPJc

###
GET https://backend.dipstick.xyz/api/v1/accounts/users/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5MDkyOTcxLCJpYXQiOjE3NzY1MDA5NzIsImp0aSI6ImI2MjljM2Y5ZTMwYjRiNDZhMmM2NDY2ZWI0MGQ4NGZiIiwiaWQiOiI4NGI3MWNmZC1iMDMwLTQ2ZDAtYjEyYy01OTY1YTE0YTAzZTQifQ.CkUCY5Xf5NAblk7YkcGfqRRWzX4tTl2FCL_ShPxQPJc
 
###
GET https://backend.dipstick.xyz/api/v1/students/students/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5MDkyOTcxLCJpYXQiOjE3NzY1MDA5NzIsImp0aSI6ImI2MjljM2Y5ZTMwYjRiNDZhMmM2NDY2ZWI0MGQ4NGZiIiwiaWQiOiI4NGI3MWNmZC1iMDMwLTQ2ZDAtYjEyYy01OTY1YTE0YTAzZTQifQ.CkUCY5Xf5NAblk7YkcGfqRRWzX4tTl2FCL_ShPxQPJc
 

###
POST https://backend.dipstick.xyz/api/v1/accounts/users/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5MDkyOTcxLCJpYXQiOjE3NzY1MDA5NzIsImp0aSI6ImI2MjljM2Y5ZTMwYjRiNDZhMmM2NDY2ZWI0MGQ4NGZiIiwiaWQiOiI4NGI3MWNmZC1iMDMwLTQ2ZDAtYjEyYy01OTY1YTE0YTAzZTQifQ.CkUCY5Xf5NAblk7YkcGfqRRWzX4tTl2FCL_ShPxQPJc
Content-Type: application/json

{
  "email": "student.demo@example.com",
  "password": "Test@1234",
  "full_name": "Demo Student",
  "short_name": "Student",
  "phone": "01722222222",
  "personal_number": "STU-1001",

  "gender": "male",
  "blood_group": "O+",
  "marital_status": "single",

  "birth_date": "2005-06-15",
  "place_of_birth": "Dhaka",
  "country": "Bangladesh",

  "present_address": "Dhaka",
  "permanent_address": "Noakhali",

  "wing": "civil",  

  "joining_date": "2026-04-14",
  "date_of_enrolment": "2026-04-14",
  "current_status": "active" 
}




###
GET https://backend.dipstick.xyz/api/v1/students/students/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5MDkyOTcxLCJpYXQiOjE3NzY1MDA5NzIsImp0aSI6ImI2MjljM2Y5ZTMwYjRiNDZhMmM2NDY2ZWI0MGQ4NGZiIiwiaWQiOiI4NGI3MWNmZC1iMDMwLTQ2ZDAtYjEyYy01OTY1YTE0YTAzZTQifQ.CkUCY5Xf5NAblk7YkcGfqRRWzX4tTl2FCL_ShPxQPJc
Content-Type: application/json

{
  "user": "98f61a3e-85c1-486e-9088-ff62a3f1d8ac",

  "second_language": "English",
  "date_of_commission": "2026-04-14",
  "date_of_joining_accs": "2026-04-14",

  "father_full_name": "Hello Father",
  "father_phone": "01712345678",
  "father_address": "Sylhet",
  "father_profession": "Professor",

  "mother_full_name": "Hello Mother",
  "mother_phone": "01798765432",
  "mother_address": "Sylhet",
  "mother_profession": "Housewife",

  "passport_number": "A18205212",
  "passport_issue_date": "2026-04-14",
  "passport_place": "Dhaka",
  "passport_expiry_date": "2030-04-14",

  "health_condition": "Good",
  "other_info": "N/A",

  "is_active": false,
  "index_no": 1,

  "student_type": "6e9e3af2-c1eb-42ae-b850-900df3c984de",    
  "batch": "6cf906ea-9f02-4464-8db7-0d8bd522a2ea"           
}



###
POST https://backend.dipstick.xyz/api/v1/accounts/users/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5MDkyOTcxLCJpYXQiOjE3NzY1MDA5NzIsImp0aSI6ImI2MjljM2Y5ZTMwYjRiNDZhMmM2NDY2ZWI0MGQ4NGZiIiwiaWQiOiI4NGI3MWNmZC1iMDMwLTQ2ZDAtYjEyYy01OTY1YTE0YTAzZTQifQ.CkUCY5Xf5NAblk7YkcGfqRRWzX4tTl2FCL_ShPxQPJc
Content-Type: application/json

{
  "email": "staff.demo@example.com",
  "password": "Test@1234",
  "full_name": "Demo Staff",
  "short_name": "Staff You",
  "phone": "01711111111",
  "personal_number": "PN-2001",

  "rank": "f7e64226-7174-4311-898f-5ddf489bbc44",
  "gender": "male",
  "blood_group": "B+",
  "marital_status": "married",

  "birth_date": "1990-01-01",
  "place_of_birth": "Dhaka",
  "country": "Bangladesh",

  "present_address": "Dhaka",
  "permanent_address": "Khulna",

  "current_unit": 1,
  "wing": "army",
  "appointment": 1,

  "joining_date": "2026-04-14",
  "date_of_enrolment": "2026-04-14",
  "current_status": "active",

  "role_slug": "staff"
}


### Login
POST http://localhost:8020/api/v1/accounts/login/
Content-Type: application/json

{
    "email": "teacher@gmail.com",
    "password": "123456789"
}

### Token Refresh
POST http://localhost:8020/api/v1/accounts/refresh/
Content-Type: application/json

{
     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3ODUxOTQxMSwiaWF0IjoxNzc1OTI3NDExLCJqdGkiOiJkMGFhMDJjYTE1ZGI0OTMzOGIzNjY5NjQxNDAzYjQ5OSIsImlkIjoiYjRjZjRlYzctNmFjOS00ZDNiLWJjYTUtMWQ3NTRhZTJhNTg3In0.Fq88aHyPUZPAlhCPgs44L6wOsje-0towNjhDpUOsfRQ"
}

### OTP Verification
POST http://localhost:8020/api/v1/accounts/verify-otp/
Content-Type: application/json

{
    "email": "anmamuncoder@gmail.com",
    "otp": "590240"
}

### Resend OTP
POST http://localhost:8020/api/v1/accounts/resend-otp/
Content-Type: application/json

{
    "email": "anmamuncoder@gmail.com"
}


# -------------

###  
POST http://localhost:8020/api/v1/accounts/forgot-password/
Content-Type: application/json

{
    "email": "anmamuncoder@gmail.com"
}

###  
POST http://localhost:8020/api/v1/accounts/verify-reset-otp/
Content-Type: application/json

{
    "email": "anmamuncoder@gmail.com",
    "otp": "433191"
}

###  
POST http://localhost:8020/api/v1/accounts/reset-password/
Content-Type: application/json

{
    "reset_token": "StrpPRUp3XAGUTCZdzsMNX6vTPa0ht3nk6Myj0xe7Pg",
    "new_password": "123456789"
}


# -------------
# Authentication:

###
PUT http://localhost:8020/api/v1/accounts/password/change/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3ODg5OTY2LCJpYXQiOjE3NzUyOTc5NjYsImp0aSI6IjVmNGI5Mjc3Nzk5YzQxY2JhYjI2ZGNmYTA1MDIwNmFlIiwiaWQiOiI0M2M4NGYyMC1mNDU5LTRmN2QtOTJhMy03ZDViNzc2NTNjMDAifQ.vVN79GblndwBXvbhiplmZ7lh2QBU6CcJM51mBV5AUE4
Content-Type: application/json

{
    "current_password":"1234567890",
    "new_password":"123456789012",
    "confirm_password":"123456789012"
}

#success message:
# {
#   "success": true,
#   "message": "Password updated successfully.",
#   "data": null
# }

# current password is wrong if;
# {
#   "status": false,
#   "errors": {
#     "current_password": [
#       "Current password is incorrect."
#     ]
#   }
# }

###
POST http://localhost:8020/api/v1/accounts/email/change/
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
    "new_email":"fokhrul.dev@gmail.com",
    "password":"123456789"
}

# success message
# {
#   "success": true,
#   "message": "OTP sent to anmamuncoder@gmail.com.",
#   "data": null
# }

# error if same email:
# {
#   "status": false,
#   "errors": {
#     "new_email": [
#       "New email must be different from current email."
#     ]
#   }
# }
# if wrong password:

# {
#   "status": false,
#   "errors": {
#     "password": [
#       "Incorrect password."
#     ]
#   }
# }
# if use this email ayone 

# {
#   "status": false,
#   "errors": {
#     "new_email": [
#       "This email is already in use."
#     ]
#   }
# }


###
POST http://localhost:8020/api/v1/accounts/email/change/verify/
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
    "otp":"373579"
}

# {
#   "success": true,
#   "message": "Email updated successfully.",
#   "data": null
# }

# {
#   "status": false,
#   "errors": {
#     "otp": [
#       "Invalid OTP."
#     ]
#   }
# }

@superuser_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwMjQ3NDYzLCJpYXQiOjE3Nzc2NTU0NjMsImp0aSI6IjJlYjY0MjFhOGIzYTRlNmVhMTExZTU5ODI5NzNjYjkyIiwiaWQiOiI5NDRiMTBlNi00MjJhLTQ5OGMtOGMwNi01ZjgyOTMyMjQ1YmYifQ.T8lDkYNsTBDaAsX5Qr_KFYv8KpmwjbHgx6gdcPSD3ms


# --------------------------------------
# Permissions  - Only Admin
# --------------------------------------
### admin
GET http://localhost:8020/api/v1/accounts/users/
Authorization:  Bearer {{superuser_token}}

### admin
GET http://localhost:8020/api/v1/rbac/permissions/accounts_ranks:create/
Authorization:  Bearer {{superuser_token}}
# {
#   "id": "3096301b-5f43-42aa-9ea0-89966c239f1d",
#   "slug": "order:delete",
#   "name": "Delete order test",
#   "resource": "order",
#   "action": "delete",
#   "description": "",
#   "created_at": "2026-03-23T00:12:47.258577+06:00",
#   "updated_at": "2026-03-24T15:25:03.821205+06:00"
# }

### admin
PATCH  http://localhost:8020/api/v1/rbac/permissions/order:delete/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw
Content-Type: application/json

{
    "name":"Delete order test" 
  
}

### admin
PATCH  http://localhost:8020/api/v1/rbac/permissions/order:delete/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw
Content-Type: application/json

{
    "name":"Delete order test" 
}


# ---------------------------------
# Roles - only for Admin
# ---------------------------------


### 
GET http://localhost:8020/api/v1/rbac/roles/
Authorization:  Bearer {{access_token}}


#   {
#     "id": "71b00eaa-526f-48bc-be0e-795fe2194930",
#     "name": "Editor",
#     "slug": "editor",
#     "permissions": [
#       "order:create",
#       "product:create",
#       "product:update",
#       "product:view"
#     ],
#     "description": "",
#     "created_at": "2026-03-23T00:12:47.290573+06:00",
#     "updated_at": "2026-03-24T01:33:34.241815+06:00"
#   },

###
POST http://localhost:8020/api/v1/rbac/roles/ 
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw
Content-Type: application/json

###
GET http://localhost:8020/api/v1/rbac/roles/teacher/
Authorization:  Bearer {{superuser_token}}

###
GET  http://localhost:8020/api/v1/rbac/roles/editor/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw

###
DELETE  http://localhost:8020/api/v1/rbac/roles/slug/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ0MzQ0LCJpYXQiOjE3NzQzNDM0NDQsImp0aSI6ImNmZjhmNWM4YzE2ZDRlMGRhNTI2MzkwYjAzY2QyODU5IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.p_UCRa3KKh7CnfwotBW1uMB7OH8BpnspCwZkJt4b_Qw

# ---------------------------------
# UserRole - only for Admin
# ---------------------------------
GET http://localhost:8020/api/v1/rbac/user-roles/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ1NDgwLCJpYXQiOjE3NzQzNDQ1ODAsImp0aSI6IjQ0YjIyY2NlY2E0MzRmYjZhOGZlNTU3MjU1ZmZmODU3IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.kDW2V0l3-p-olOBSNB8o4Q91WZLFJ9bnwG38jIegIqQ

### admin
GET http://localhost:8020/api/v1/rbac/user-roles/ae6ecf0d-3a7d-4b56-bcfc-0beff9255ac6/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ1NDgwLCJpYXQiOjE3NzQzNDQ1ODAsImp0aSI6IjQ0YjIyY2NlY2E0MzRmYjZhOGZlNTU3MjU1ZmZmODU3IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.kDW2V0l3-p-olOBSNB8o4Q91WZLFJ9bnwG38jIegIqQ

# {
#   "id": "ae6ecf0d-3a7d-4b56-bcfc-0beff9255ac6",
#   "user": "anmamuncoder@gmail.com",
#   "role": "manager"
# }

### admin
PATCH http://localhost:8020/api/v1/rbac/user-roles/ae6ecf0d-3a7d-4b56-bcfc-0beff9255ac6/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ1NDgwLCJpYXQiOjE3NzQzNDQ1ODAsImp0aSI6IjQ0YjIyY2NlY2E0MzRmYjZhOGZlNTU3MjU1ZmZmODU3IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.kDW2V0l3-p-olOBSNB8o4Q91WZLFJ9bnwG38jIegIqQ
Content-Type: application/json

{  
    "role": "editor"
}

### admin
POST http://localhost:8020/api/v1/rbac/user-roles/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MzQ1NDgwLCJpYXQiOjE3NzQzNDQ1ODAsImp0aSI6IjQ0YjIyY2NlY2E0MzRmYjZhOGZlNTU3MjU1ZmZmODU3IiwiaWQiOiJmNTEzNmYyOS01ZTY4LTRjMTUtODE3YS0wZjk4MDNmOWY2NzQifQ.kDW2V0l3-p-olOBSNB8o4Q91WZLFJ9bnwG38jIegIqQ
Content-Type: application/json

{  
  "user": "anmamuncoder@gmail.com",
  "role": "editor"
}

### admin
GET http://localhost:8020/api/v1/rbac/user-roles-assign/
Authorization:  Bearer {{superuser_token}}
 

### admin
POST  http://localhost:8020/api/v1/rbac/user-roles-assign/
Authorization:  Bearer {{superuser_token}}
Content-Type: application/json

{
    "user": "anmamuncoder@gmail.com",
    "role": "teacher"
}

### admin
PATCH   http://localhost:8020/api/v1/rbac/user-roles-assign/a56a30a6-f86a-4ea4-b891-6e1d5d50ad06/
Authorization:  Bearer {{superuser_token}}
Content-Type: application/json

{ 
    "role": "librarian"
}


# ---------------------------------
# User Ranks
# ---------------------------------
###
GET http://localhost:8020/api/v1/students/students/
Authorization:  Bearer {{superuser_token}}

### BASE URL
@studentUrl = http://127.0.0.1:8000/api/v1/students

@admin-token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4MTgyNTQ0LCJpYXQiOjE3NzU1OTA1NDQsImp0aSI6ImQ2NTk0YzVkNTgyZTQwMWE4YmFjYTM1OWY2MjhhZGQ4IiwiaWQiOiI0ZWViMzc1YS1kNzBjLTQ2ODMtODk5YS1kZWFlYzFmZmM0YjEifQ.PVwkA6Y0Wd8gQN1Dwc10AgZ5itmGchfunTABUkUnXwI

 
 
# Permissions
ALL_METHOD http://localhost:8020/api/v1/rbac/roles/ 
GET http://localhost:8020/api/v1/rbac/permissions/


# Roles
ALL_METHOD http://localhost:8020/api/v1/accounts/ranks/
ALL_METHOD http://localhost:8020/api/v1/accounts/users/

# Student Related
ALL http://localhost:8020/api/v1/students/students/
ALL http://localhost:8020/api/v1/students/student-types/
ALL http://localhost:8020/api/v1/students/student-groups/
ALL http://localhost:8020/api/v1/students/activities/
ALL http://localhost:8020/api/v1/students/spouses/
ALL http://localhost:8020/api/v1/students/qualifications/
ALL http://localhost:8020/api/v1/students/bank-accounts/
ALL http://localhost:8020/api/v1/students/military-qualifications/
ALL http://localhost:8020/api/v1/students/service-records/
ALL http://localhost:8020/api/v1/students/awards/
ALL http://localhost:8020/api/v1/students/un-missions/
ALL http://localhost:8020/api/v1/students/countries-visited/


# Courses 
 
ALL http://localhost:8020/api/v1/courses/courses/
ALL http://localhost:8020/api/v1/courses/subjects/
ALL http://localhost:8020/api/v1/courses/modules/
ALL http://localhost:8020/api/v1/courses/syllabus/
ALL http://localhost:8020/api/v1/courses/detail-syllabus/
ALL http://localhost:8020/api/v1/courses/batches/




# Exams Module
http://localhost:8020/api/v1/exams/exam-grades/
http://localhost:8020/api/v1/exams/exam-schedules/
http://localhost:8020/api/v1/exams/exams/
http://localhost:8020/api/v1/exams/exam-attendance/

# Time Tables Module

http://localhost:8020/api/v1/time_tables/govt-holidays/
http://localhost:8020/api/v1/time_tables/training-schedules/


###
GET http://localhost:8020/api/v1/accounts/users/
Authorization:  Bearer {{superuser_token}}


###
GET http://localhost:8020/api/v1/accounts/users/self/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwMjQ5NTAxLCJpYXQiOjE3Nzc2NTc1MDEsImp0aSI6ImJiNzA1YzFlYjBmZDQ1NjhiNGU4NGNmYjY0NTczZjI4IiwiaWQiOiI1NWFhY2E2ZC1lOTdmLTQyZmUtYjkxYy0zMTkwYWQwNDcyOWIifQ.Suy-BHamtVwQ4mHJELkt7uTIWXju_ujor0qdu61f5vs


###
POST http://localhost:8020/api/v1/accounts/users/
Authorization:  Bearer {{superuser_token}}
Content-Type: application/json

{ 
    "email": "teacher@gmail.com",
    "password": "123456789",
    "role_slug": "teacher"
}

