# Generated by Django 6.0.2 on 2026-05-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/documents/'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='lecture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='others',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='practical',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_syllabus', to='course.subject'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='written',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_blocks', to='course.course'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_blocks', to='course.module'),
        ),
        migrations.DeleteModel(
            name='DetailSyllabus',
        ),
    ]
