# Generated by Django 6.0.2 on 2026-05-14 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_syllabus_document_syllabus_lecture_syllabus_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_syllabus', to='course.batch'),
        ),
    ]
