# Generated by Django 6.0.2 on 2026-05-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_syllabus_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_subjects', to='course.batch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
