# Generated by Django 6.0.2 on 2026-05-18 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_subject_batch_subject_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='subject',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_mark',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_mark',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_mark',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='viva_mark',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='written_mark',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
