# Generated by Django 6.0.2 on 2026-05-23 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_subject_credit_subject_instructor_subject_pass_mark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='pass_mark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='total_mark',
        ),
        migrations.AddField(
            model_name='batch',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_batches', to='course.batch'),
        ),
        migrations.AddField(
            model_name='module',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='trade',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='lecture_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='method',
            field=models.CharField(choices=[('PRACTICAL', 'Practical'), ('LECTURAL', 'Lectural'), ('WRITTEN', 'Written'), ('OTHER', 'Other')], default='LECTURAL', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_subjects', to='course.module'),
        ),
        migrations.AddField(
            model_name='subject',
            name='other_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='written_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practical_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='viva_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='written_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
