# Generated by Django 6.0.2 on 2026-05-11 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_syllabus_document_syllabus_lecture_syllabus_others_and_more'),
        ('student', '0008_countryvisited_student_student_current_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index_no', models.PositiveIntegerField(blank=True, null=True)),
                ('observation_date', models.DateField()),
                ('observation_time', models.TimeField(blank=True, null=True)),
                ('observation_note', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('observation_mark', models.FloatField(default=0.0)),
                ('point', models.FloatField(default=0.0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_sheets', to='course.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_sheets', to='course.course')),
                ('observation_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_observations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='syllabus/documents/')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_programme', to='course.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_programme', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_marks', models.FloatField(default=0.0)),
                ('obtained_marks', models.FloatField(default=0.0)),
                ('observation_marks', models.FloatField(default=0.0)),
                ('weightage_marks', models.FloatField(default=0.0)),
                ('final_percentage', models.FloatField(default=0.0)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('result_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='course.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='course.course')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='student.student')),
                ('training_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_results', to='training.trainingprogramme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeightageDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('practical_marks', models.PositiveIntegerField(default=0)),
                ('theory_marks', models.PositiveIntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('document', models.FileField(blank=True, null=True, upload_to='syllabus/documents/')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weightage_distributions', to='course.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weightage_distributions', to='course.course')),
                ('training_programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightage_distributions', to='training.trainingprogramme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
