# Generated by Django 6.0.2 on 2026-05-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_syllabus_document_syllabus_lecture_syllabus_others_and_more'),
        ('student', '0008_countryvisited_student_student_current_unit_and_more'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalresult',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='course.batch'),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='course.course'),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='student.student'),
        ),
        migrations.AlterField(
            model_name='observationsheet',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_sheets', to='course.batch'),
        ),
        migrations.AlterField(
            model_name='observationsheet',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_sheets', to='course.course'),
        ),
        migrations.AlterField(
            model_name='observationsheet',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='student.student'),
        ),
        migrations.AlterField(
            model_name='weightagedistribution',
            name='training_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weightage_distributions', to='training.trainingprogramme'),
        ),
    ]
