# Generated by Django 6.0.2 on 2026-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_finalresult_batch_alter_finalresult_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/documents/'),
        ),
    ]
