# Generated by Django 6.0.2 on 2026-05-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_finalresult_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationsheet',
            name='observation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingprogramme',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
