# Generated by Django 6.0.2 on 2026-05-23 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_subject_pass_mark_remove_subject_total_mark_and_more'),
        ('training', '0004_alter_observationsheet_observation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightagedistribution',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='weightagedistribution',
            name='course',
        ),
        migrations.RemoveField(
            model_name='weightagedistribution',
            name='training_programme',
        ),
        migrations.AddField(
            model_name='weightagedistribution',
            name='full_mark',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weightagedistribution',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightagedistribution',
            name='observation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_weightage_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weightagedistribution',
            name='pass_mark',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weightagedistribution',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weightage_distribution', to='course.subject'),
        ),
        migrations.AddField(
            model_name='weightagedistribution',
            name='wt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddConstraint(
            model_name='weightagedistribution',
            constraint=models.UniqueConstraint(fields=('subject',), name='unique_subject_weightage_distribution'),
        ),
    ]
