# Generated by Django 6.0.2 on 2026-05-31 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_subject_pass_mark_remove_subject_total_mark_and_more'),
        ('training', '0005_remove_weightagedistribution_batch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightagedistribution',
            options={'ordering': ['subject__name']},
        ),
        migrations.RemoveConstraint(
            model_name='weightagedistribution',
            name='unique_subject_weightage_distribution',
        ),
        migrations.AlterField(
            model_name='weightagedistribution',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weightage_distribution', to='course.subject'),
        ),
    ]
