# Generated by Django 6.0.2 on 2026-06-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_weightagedistribution_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightagedistribution',
            name='total_marks',
        ),
    ]
