# Generated by Django 6.0.2 on 2026-06-01 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_subject_pass_mark_remove_subject_total_mark_and_more'),
        ('exam', '0001_initial'),
        ('student', '0012_remove_batchmembership_unique_index_no_per_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='module',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='schedule',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-exam_date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='examgrade',
            options={'ordering': ['mark_from']},
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_type',
            field=models.CharField(blank=True, choices=[('b_side', 'B Side'), ('y_side', 'Y Side')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='room_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='course.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='grade_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], default='absent', max_length=20)),
                ('obtained_marks', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attended_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.exam')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='student.batchmembership')),
            ],
            options={
                'ordering': ['membership__batch__name', 'membership__index_no'],
            },
        ),
        migrations.DeleteModel(
            name='ExamAttendance',
        ),
        migrations.DeleteModel(
            name='ExamSchedule',
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam'], name='exam_examre_exam_id_82f08a_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['membership'], name='exam_examre_members_8df0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['status'], name='exam_examre_status_918c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'status'], name='exam_examre_exam_id_142db7_idx'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('membership', 'exam'), name='unique_exam_result_per_student'),
        ),
    ]
