# Generated by Django 6.0.2 on 2026-06-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_examiner'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_attendance_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], default='pending', max_length=20),
        ),
    ]
