# Generated by Django 6.0.2 on 2026-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_is_attendance_locked_alter_examresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examgrade',
            name='b_side_grade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='y_side_grade',
            field=models.CharField(max_length=20),
        ),
    ]
