# Generated by Django 6.0.2 on 2026-04-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='index_no',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
