# Generated by Django 6.0.2 on 2026-05-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_batchmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmembership',
            name='index_no',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
