# Generated by Django 6.0.2 on 2026-05-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_batchmembership_index_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchmembership',
            unique_together=set(),
        ),
    ]
