# Generated by Django 6.0.2 on 2026-05-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_parent'),
        ('student', '0005_alter_batchmembership_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmembership',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.batch'),
        ),
    ]
