# Generated by Django 4.1.13 on 2026-05-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_batchmembership_batch'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batchmembership',
            constraint=models.UniqueConstraint(fields=('student', 'batch'), name='unique_batch_per_student'),
        ),
    ]
