# Generated by Django 6.0.2 on 2026-05-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_syllabus_document_syllabus_lecture_syllabus_others_and_more'),
        ('student', '0007_batchmembership_unique_batch_per_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryvisited',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_country', to='student.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_photo',
            field=models.ImageField(blank=True, null=True, upload_to='father/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mother/'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='tc/'),
        ),
        migrations.AddField(
            model_name='unmission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='un_missions', to='student.student'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='student.student'),
        ),
        migrations.AlterField(
            model_name='batchmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_memberships', to='student.student'),
        ),
        migrations.AlterField(
            model_name='militaryqualification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='military_qualifications', to='student.student'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='student.student'),
        ),
        migrations.AddConstraint(
            model_name='batchmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('student',), name='unique_null_batch_per_student'),
        ),
    ]
