# Generated by Django 6.0.2 on 2026-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_syllabus_batch'),
        ('student', '0008_countryvisited_student_student_current_unit_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batchmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('index_no__isnull', False)), fields=('batch', 'index_no'), name='unique_index_no_per_batch'),
        ),
    ]
