# Generated by Django 6.0.2 on 2026-05-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_batchmembership_unique_index_no_per_batch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batchmembership',
            name='unique_batch_per_student',
        ),
        migrations.RemoveConstraint(
            model_name='batchmembership',
            name='unique_null_batch_per_student',
        ),
        migrations.RemoveConstraint(
            model_name='batchmembership',
            name='unique_index_no_per_batch',
        ),
        migrations.AlterField(
            model_name='batchmembership',
            name='index_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
