# Generated by Django 6.0.2 on 2026-05-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_syllabus_batch'),
        ('student', '0010_remove_batchmembership_unique_batch_per_student_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batchmembership',
            constraint=models.UniqueConstraint(fields=('student', 'batch'), name='unique_batch_per_student'),
        ),
        migrations.AddConstraint(
            model_name='batchmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('student',), name='unique_null_batch_per_student'),
        ),
        migrations.AddConstraint(
            model_name='batchmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False), ('index_no__isnull', False)), fields=('batch', 'index_no'), name='unique_index_no_per_batch'),
        ),
    ]
