# Generated by Django 6.0.2 on 2026-05-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_syllabus_batch'),
        ('student', '0011_batchmembership_unique_batch_per_student_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batchmembership',
            name='unique_index_no_per_batch',
        ),
        migrations.AddConstraint(
            model_name='batchmembership',
            constraint=models.UniqueConstraint(fields=('batch', 'index_no'), name='unique_index_no_per_batch'),
        ),
    ]
