# Generated by Django 6.0.2 on 2026-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.CharField(choices=[('administrative', 'Administrative'), ('training', 'Training'), ('other', 'Other')], default='training', max_length=20),
        ),
    ]
